;version=Overclock tool selector
;creator=Asa
;color=orange

[Sys-Clk-OC│Manager]
[안내문]
;mode=table
;spacing=5
;gap=30
'안내:'='클럭 조정 앱의 사용 유/무를 결정합니다'
''='비활성화시 오버레이를 한 번 종료합니다'

[활성화]
;mode=toggle?on
on:
    del /atmosphere/contents/420000000000000B/
    del /atmosphere/kips/loader.kip
    del /atmosphere/logs/sys-patch.log
    set-ini-val './config.ini' 'EOS Toolkit' footer Off
    set-ini-val './config.ini' 'SC Toolkit' footer Off
    mv '/config/ASAP-assist/OC/' '/atmosphere/contents/00FF0000636C6BFF/'
    mv '/config/ASAP-assist/Packages/SC Toolkit/' '/config/ASAP-assist/Packages/.offload/SC Toolkit/'
    mv '/config/ASAP-assist/Packages/EOS Toolkit/' '/config/ASAP-assist/Packages/.offload/EOS Toolkit/'
    mv '/config/ASAP-assist/Packages/.offload/System Clock+/' '/config/ASAP-assist/Packages/System Clock+/'
    mv '/switch/.overlays/.offload/sys-clk-overlay.ovl' '/switch/.overlays/'
    mv '/config/ASAP-assist/Homebrews/sys-clk-manager/' '/switch/sys-clk-manager/'
    refresh
off:
    del /atmosphere/contents/420000000000000B/
    del /atmosphere/kips/loader.kip
    del /atmosphere/logs/sys-patch.log
    set-ini-val './config.ini' 'EOS Toolkit' footer Off
    set-ini-val './config.ini' 'SC Toolkit' footer Off
    mv '/atmosphere/contents/00FF0000636C6BFF/' '/config/ASAP-assist/OC/'
    mv '/config/ASAP-assist/Packages/SC Toolkit/' '/config/ASAP-assist/Packages/.offload/SC Toolkit/'
    mv '/config/ASAP-assist/Packages/EOS Toolkit/' '/config/ASAP-assist/Packages/.offload/EOS Toolkit/'
    mv '/config/ASAP-assist/Packages/.offload/System Clock+/' '/config/ASAP-assist/Packages/System Clock+/'
    set-ini-val '/config/ASAP-assist/Packages/System Clock+/config.ini' '활성화' footer Off
    mv '/switch/.overlays/sys-clk-overlay.ovl' '/switch/.overlays/.offload/'
    mv '/switch/sys-clk-manager/' '/config/ASAP-assist/Homebrews/sys-clk-manager/'
    exit


[Loader.kip 편집 도구]
[경고문 Pt1]
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '낸드에 치명적인 손상을 줄 수 있습니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ㅤㅤㅤㅤㅤㅤ'

[경고문 Pt2]
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'' = '반드시! 에뮤에서 안정성 확인 후, 시스낸드 적용'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ ㅤㅤㅤㅤㅤㅤ'

[경고문 강조]
;mode=table
;spacing=0
;gap=10
;info_text_color=00FFDD
'' = '시스낸드에서의 편집/사용을 권장하지 않습니다'
'' = ''

[안내문]
;mode=table
;spacing=5
;gap=30
'안내:'='Loader.kip 적용을 위해 재부팅합니다'

[EOS Toolkit]
;mode=toggle
on:
    del /atmosphere/kips/loader.kip
    cp '/backup/kips/.EOS/loader.kip' '/atmosphere/kips/'
    cp '/atmosphere/contents/010B6ECF3B30D000/02/boot2.flag' '/atmosphere/contents/420000000000000B/flags/'
    cp '/atmosphere/contents/010B6ECF3B30D000/02/exefs.nsp' '/atmosphere/contents/420000000000000B/'
    mv '/config/ASAP-assist/Packages/SC Toolkit/' '/config/ASAP-assist/Packages/.offload/SC Toolkit/'
    mv '/config/ASAP-assist/Packages/.offload/EOS Toolkit/' '/config/ASAP-assist/Packages/EOS Toolkit/'
    set-ini-val './config.ini' 'EOS Toolkit' footer On
    set-ini-val './config.ini' 'SC Toolkit' footer Off
    mv '/config/ASAP-assist/Packages/System Clock+/' '/config/ASAP-assist/Packages/.offload/System Clock+/'
    reboot boot '커펌 (eMMC/SD Card)'
off:
    del /atmosphere/contents/420000000000000B/
    del /atmosphere/kips/loader.kip
    del /atmosphere/logs/sys-patch.log
    mv '/config/ASAP-assist/Packages/SC Toolkit/' '/config/ASAP-assist/Packages/.offload/SC Toolkit/'
    mv '/config/ASAP-assist/Packages/EOS Toolkit/' '/config/ASAP-assist/Packages/.offload/EOS Toolkit/'
    set-ini-val './config.ini' 'EOS Toolkit' footer Off
    set-ini-val './config.ini' 'SC Toolkit' footer Off
    mv '/config/ASAP-assist/Packages/.offload/System Clock+/' '/config/ASAP-assist/Packages/System Clock+/'
    reboot boot '커펌 (eMMC/SD Card)'

[SC Toolkit]
;mode=toggle
on:
    del /atmosphere/kips/loader.kip
    cp '/backup/kips/.SC/loader.kip' '/atmosphere/kips/'
    cp '/atmosphere/contents/010B6ECF3B30D000/02/boot2.flag' '/atmosphere/contents/420000000000000B/flags/'
    cp '/atmosphere/contents/010B6ECF3B30D000/02/exefs.nsp' '/atmosphere/contents/420000000000000B/'
    mv '/config/ASAP-assist/Packages/EOS Toolkit/' '/config/ASAP-assist/Packages/.offload/EOS Toolkit/'
    mv '/config/ASAP-assist/Packages/.offload/SC Toolkit/' '/config/ASAP-assist/Packages/SC Toolkit/'
    set-ini-val './config.ini' 'EOS Toolkit' footer Off
    set-ini-val './config.ini' 'SC Toolkit' footer On
    mv '/config/ASAP-assist/Packages/System Clock+/' '/config/ASAP-assist/Packages/.offload/System Clock+/'
    reboot boot '커펌 (eMMC/SD Card)'
off:
    del /atmosphere/contents/420000000000000B/
    del /atmosphere/kips/loader.kip
    del /atmosphere/logs/sys-patch.log
    mv '/config/ASAP-assist/Packages/SC Toolkit/' '/config/ASAP-assist/Packages/.offload/SC Toolkit/'
    mv '/config/ASAP-assist/Packages/EOS Toolkit/' '/config/ASAP-assist/Packages/.offload/EOS Toolkit/'
    set-ini-val './config.ini' 'EOS Toolkit' footer Off
    set-ini-val './config.ini' 'SC Toolkit' footer Off
    mv '/config/ASAP-assist/Packages/.offload/System Clock+/' '/config/ASAP-assist/Packages/System Clock+/'
    reboot boot '커펌 (eMMC/SD Card)'