;title=OC Toolkit SC
;version=1.3.2
;creator=ppkantorski, B3711
;credits=meha, lineon, efosamark, i3sey, irene, redraz
;color=pink

[백업 시스템]
[*3번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s3_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_3.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s3_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot3]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_3.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot3]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot3]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_3.ini'
exec backup
del '/backup/kips/SC_s3_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s3_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_3.ini' 
#set-ini-val './config.ini' '설정 복원?slot3' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot3]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_3.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s3_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s3_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot3]
;mode=default
del '/backup/kips/.SC/slot_3.ini'
del '/backup/kips/SC_s3_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot3' footer
remove-ini-key './config.ini' '설정 백업?slot3' footer
remove-ini-key './config.ini' '설정 복원?slot3' footer
refresh

[*4번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s4_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_4.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s4_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot4]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_4.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot4]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot4]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_4.ini'
exec backup
del '/backup/kips/SC_s4_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s4_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_4.ini' 
#set-ini-val './config.ini' '설정 복원?slot4' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot4]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_4.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s4_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s4_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot4]
;mode=default
del '/backup/kips/.SC/slot_4.ini'
del '/backup/kips/SC_s4_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot4' footer
remove-ini-key './config.ini' '설정 백업?slot4' footer
remove-ini-key './config.ini' '설정 복원?slot4' footer
refresh


[*5번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s5_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_5.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s5_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot5]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_5.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot5]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot5]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_5.ini'
exec backup
del '/backup/kips/SC_s5_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s5_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_5.ini' 
#set-ini-val './config.ini' '설정 복원?slot5' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot5]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_5.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s5_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s5_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot5]
;mode=default
del '/backup/kips/.SC/slot_5.ini'
del '/backup/kips/SC_s5_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot5' footer
remove-ini-key './config.ini' '설정 백업?slot5' footer
remove-ini-key './config.ini' '설정 복원?slot5' footer
refresh


[*6번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s6_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_6.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s6_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot6]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_6.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot6]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot6]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_6.ini'
exec backup
del '/backup/kips/SC_s6_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s6_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_6.ini' 
#set-ini-val './config.ini' '설정 복원?slot6' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot6]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_6.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s6_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s6_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot6]
;mode=default
del '/backup/kips/.SC/slot_6.ini'
del '/backup/kips/SC_s6_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot6' footer
remove-ini-key './config.ini' '설정 백업?slot6' footer
remove-ini-key './config.ini' '설정 복원?slot6' footer
refresh


[*7번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s7_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_7.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s7_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot7]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_7.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot7]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot7]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_7.ini'
exec backup
del '/backup/kips/SC_s7_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s7_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_7.ini' 
#set-ini-val './config.ini' '설정 복원?slot7' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot7]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_7.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s7_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s7_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot7]
;mode=default
del '/backup/kips/.SC/slot_7.ini'
del '/backup/kips/SC_s7_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot7' footer
remove-ini-key './config.ini' '설정 백업?slot7' footer
remove-ini-key './config.ini' '설정 복원?slot7' footer
refresh


[*8번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s8_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_8.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s8_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot8]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_8.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot8]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot8]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_8.ini'
exec backup
del '/backup/kips/SC_s8_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s8_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_8.ini' 
#set-ini-val './config.ini' '설정 복원?slot8' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot8]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_8.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s8_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s8_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot8]
;mode=default
del '/backup/kips/.SC/slot_8.ini'
del '/backup/kips/SC_s8_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot8' footer
remove-ini-key './config.ini' '설정 백업?slot8' footer
remove-ini-key './config.ini' '설정 복원?slot8' footer
refresh


[*9번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/SC_s9_loader.kip'
'' = 'SD:/backup/kips/.SC/slot_9.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/SC_s9_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot9]
;mode=forwarder
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_9.ini' '/backup/kips/.SC/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot9]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot9]
;mode=slot
del /backup/kips/.SC/tmp.ini
del '/backup/kips/.SC/slot_9.ini'
exec backup
del '/backup/kips/SC_s9_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/SC_s9_loader.kip' 
mv '/backup/kips/.SC/tmp.ini' '/backup/kips/.SC/slot_9.ini' 
#set-ini-val './config.ini' '설정 복원?slot9' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot9]
;mode=slot
try:
del '/backup/kips/.SC/tmp.ini'
cp '/backup/kips/.SC/slot_9.ini' '/backup/kips/.SC/tmp.ini' 
exec restore
del '/backup/kips/.SC/tmp.ini'
exec boot
del '/backup/kips/SC_s9_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/SC_s9_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot9]
;mode=default
del '/backup/kips/.SC/slot_9.ini'
del '/backup/kips/SC_s9_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot9' footer
remove-ini-key './config.ini' '설정 백업?slot9' footer
remove-ini-key './config.ini' '설정 복원?slot9' footer
refresh