;title=OC Toolkit SC
;version=1.3.2
;creator=ppkantorski, B3711
;credits=meha, lineon, efosamark, i3sey, irene, redraz
;color=pink

[주의 사항]
[안내문]
;mode=table
;gap=10
'안내:' = '설정 값 저장을 위해 재부팅이 필요합니다'

[@설정]
[RAM]
[*타이밍]
;mode=forwarder
package_source './timings.ini'

[RAM]
[*DRAM]
;mode=option
json_file_source './mariko/ram_dram_timing.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 64 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*최대 클럭?RAMmariko]
;system=mariko
;mode=option
json_file_source './mariko/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 80 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*최대 클럭?RAMerista]
;system=erista
;mode=option
json_file_source './erista/ram_freqs.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 76 {json_file_source(*,dec)}
set-footer '{json_file_source(*,name)}'

[*Vddq]
;system=mariko
;mode=option
json_file_source './mariko/ram_vddq.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 72 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Vdd2]
;mode=option
mariko:
json_file_source './mariko/ram_vdd2.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 68 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
erista:
json_file_source './erista/ram_vdd2.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 68 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*EMC DVB 테이블]
;mode=option
mariko:
list_source '(0, 1, 2, 3, 4)'
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 84 0{list_source(*)}
set-footer '{list_source(*)}'
erista:
list_source '(0, 1, 2, 3, 4, 5)'
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 84 0{list_source(*)}
set-footer '{list_source(*)}'


[CPU]
[*언더볼트 레벨?CPU]
;mode=option
mariko:
list_source '(0, 1, 2, 3, 4, 5, 6, 7, 8)'
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 12 0{list_source(*)}
set-footer '{list_source(*)}'
erista:
list_source '(0, 1, 2, 3, 4, 5)'
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 12 0{list_source(*)}
set-footer '{list_source(*)}'

[*고주파 언더볼트 레벨?CPU]
;system=mariko
;mode=option
json_file_source './mariko/cpu_high_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 252 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*저주파 최소 전압?CPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/cpu_low_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 24 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*최소 전압?CPUerista]
;system=erista
;mode=option
json_file_source './erista/cpu_low_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 16 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*고주파 최소 전압?CPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/cpu_high_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 28 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*전압 제한?CPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/cpu_voltages.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 32 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*전압 제한?CPUerista]
;system=erista
;mode=option
json_file_source './erista/cpu_voltages.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 20 {json_file_source(*,dec)}
set-footer '{json_file_source(*,name)}'

[*부스트 클럭?CPU]
;mode=option
mariko:
json_file_source './mariko/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 8 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
erista:
json_file_source './erista/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 8 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'


[GPU]
[*언더볼트 레벨?GPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/gpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 40 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*언더볼트 레벨?GPUerista]
;system=erista
;mode=option
json_file_source './erista/gpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 36 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*최소 전압?GPUmariko]
;system=mariko
;mode=option
json_file_source './mariko/gpu_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 56 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*최소 전압?GPUerista]
;system=erista
;mode=option
json_file_source './erista/gpu_vmin.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 48 {json_file_source(*,dec)}
set-footer '{json_file_source(*,name)}'

[*최대 전압?GPU]
;system=mariko
;mode=option
json_file_source './mariko/gpu_vmax.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 60 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*Speedo?GPU]
;system=mariko
;mode=option
json_file_source './mariko/gpu_speedo.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 52 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*전압 오프셋]
;mode=option
json_file_source './mariko/gpu_volt_offset.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 44 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'

[*커스텀 테이블]
;mode=forwarder
package_source './custom_table.ini'



[@도구]
[추가 설정]
[*설정 값 확인]
;mode=forwarder
package_source './info.ini'

[*Sys-Clk 설정]
;mode=forwarder
package_source './sys-clk_settings.ini'

[*loader.kip 프로파일]
;mode=forwarder
package_source './backup.ini'

[*System Clock+]
;mode=forwarder
package_source '/config/ASAP-assist/Packages/.offload/System Clock+/package.ini'


[크레딧]
[개발자]
;mode=table
;background=false
;spacing=0
;gap=0
;info_text_color=00FFDD
'개발자:' = 'ppkantorski, B3711, edit by Asa'
'' = ''

[기여자]
;mode=table
;background=false
;spacing=5
'기여자:' = 'MestreYodaRossi, meha, lineon'
'' = 'efosamark, i3sey, irene, redraz'