;title=OC Toolkit SC
;version=1.3.2
;creator=ppkantorski, B3711
;credits=meha, lineon, efosamark, i3sey, irene, redraz
;color=pink

[@Sys-clk 설정]
[Sys-clk 설정]
[경고문]
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '부스트 옵션의 사용을 권장하지 않습니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ'

[안내문]
;mode=table
;spacing=5
;gap=30
'언캡│무제한:' = '클럭 상한 해제'
'부스트:' = '클럭 부스트'
'동기화:' = 'ReverseNX-RT 싱크 동기화'

[클럭 언캡?sys-clk]
;mode=toggle
on:
set-ini-val /config/sys-clk/config.ini values uncapped_clocks 1
off:
set-ini-val /config/sys-clk/config.ini values uncapped_clocks 0

[클럭 무제한?sys-clk]
;mode=toggle
on:
set-ini-val /config/sys-clk/config.ini values unrestricted_handheld_clocks 1
off:
set-ini-val /config/sys-clk/config.ini values unrestricted_handheld_clocks 0

[부스트 모드?sys-clk]
;mode=toggle
on:
set-ini-val /config/sys-clk/config.ini values override_boost_mode 1
off:
set-ini-val /config/sys-clk/config.ini values override_boost_mode 0

[CPU 자동 부스트]
;mode=toggle
on:
set-ini-val /config/sys-clk/config.ini values auto_cpu_boost 1
off:
set-ini-val /config/sys-clk/config.ini values auto_cpu_boost 0

[ReverseNX 동기화]
;mode=toggle
on:
set-ini-val /config/sys-clk/config.ini values sync_reversenx 1
off:
set-ini-val /config/sys-clk/config.ini values sync_reversenx 0



[@시스템 설정]
[시스템 설정]
[경고문]
;system=mariko
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '비활성화 + 1305 MHz 사용은 위험합니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ ㅤ'

[1305]
;system=mariko
;mode=table
;gap=30
hex_file '/atmosphere/kips/loader.kip'
json '{"00":"활성화","01":"비활성화"}'
'GPU - 1305 MHz:' = {json({hex_file(CUST,256,1)})}

[GPU 스케줄링]
;mode=toggle?on
on:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 00
set-ini-val './config.ini' 'GPU 1305 MHz' footer 'On'
refresh
off:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x0
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 01
set-ini-val './config.ini' 'GPU 1305 MHz' footer 'Off'
refresh

[GPU 1305 MHz]
;system=mariko
;mode=toggle
on:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 00
refresh
off:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 01
refresh

[컨트롤러 블루투스 동기화]
;mode=toggle?on
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x1
off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x0

[팬 커브 ( 특성 곡선 )ㅤㅤㅤㅤㅤㅤㅤ권장 온도: 54°C]
[안내문]
;mode=table
;spacing=5
;gap=30
'안내:' = '클럭에 맞춰 커브 온도를 최적화하세요'
'' = 'Tskin 제한이 60°C로 해제되었습니다'

[Tskin 타겟]
;mode=step_trackbar
;min_value=52
;max_value=60
;units=°C
set-ini-val /atmosphere/config/system_settings.ini tc use_configurations_on_fwdbg u8!0x1
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, {value}000, 128, 255], [{value}000, 1000000, 255, 255]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, {value}000, 128, 255], [{value}000, 1000000, 255, 255]]"'
set-ini-val /atmosphere/config/system_settings.ini tc holdable_tskin u32!0xEA60
set-ini-val /atmosphere/config/system_settings.ini tc touchable_tskin u32!0xEA60

[기본 설정으로 복원]
remove-ini-section /atmosphere/config/system_settings.ini tc
remove-ini-section './config.ini' 'Tskin 타겟'
refresh