;title=OC Toolkit EOS
;version=1.3.2
;creator=ppkantorski, B3711
;credits=meha, lineon, efosamark, i3sey, irene, redraz
;color=pink

[업데이트]
[안내문]
;mode=table
;spacing=5
;gap=30
hex_file '/atmosphere/kips/loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'백업 경로:' = 'SD:/backup/kips/EOS_loader.kip'
'현재 버전:' = {json({hex_file(CUST,4,1)})}

[loader.kip]
try:
download https://github.com/halop/OC_Toolkit/releases/latest/download/E.zip /config/ASAP-assist/ultrahand/downloads/
set-ini-val './config.ini' Backup Path 'upd'
clear hex_sum_cache
hex_file '/atmosphere/kips/loader.kip'
ini_file './config.ini'
mkdir /backup/kips/.EOS/
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuBoost {hex_file(CUST,8,3)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuUVL {hex_file(CUST,12,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuUVH {hex_file(CUST,252,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuVminE {hex_file(CUST,16,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuVmaxE {hex_file(CUST,20,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuVminL {hex_file(CUST,24,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuVminH {hex_file(CUST,28,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup cpuVmaxM {hex_file(CUST,32,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuUVE {hex_file(CUST,36,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuUVM {hex_file(CUST,40,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuOFF {hex_file(CUST,44,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuVminE {hex_file(CUST,48,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuSpeedo {hex_file(CUST,52,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuVminM {hex_file(CUST,56,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup gpuVmax {hex_file(CUST,60,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup DRAM {hex_file(CUST,64,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup ramVDD2 {hex_file(CUST,68,3)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup ramVDDQ {hex_file(CUST,72,3)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup ramMHzE {hex_file(CUST,76,3)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup ramMHzM {hex_file(CUST,80,3)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup DVB {hex_file(CUST,84,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T1 {hex_file(CUST,88,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T2 {hex_file(CUST,92,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T3 {hex_file(CUST,96,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T4 {hex_file(CUST,100,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T5 {hex_file(CUST,104,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T6 {hex_file(CUST,108,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T7 {hex_file(CUST,112,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T8 {hex_file(CUST,116,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup T9 {hex_file(CUST,120,1)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 76UV3 {hex_file(CUST,124,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 153UV3 {hex_file(CUST,128,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 230UV3 {hex_file(CUST,132,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 307UV3 {hex_file(CUST,136,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 384UV3 {hex_file(CUST,140,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 460UV3 {hex_file(CUST,144,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 537UV3 {hex_file(CUST,148,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 614UV3 {hex_file(CUST,152,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 691UV3 {hex_file(CUST,156,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 768UV3 {hex_file(CUST,160,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 844UV3 {hex_file(CUST,164,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 921UV3 {hex_file(CUST,168,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 998UV3 {hex_file(CUST,172,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 1075UV3 {hex_file(CUST,176,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 1152UV3 {hex_file(CUST,180,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 1228UV3 {hex_file(CUST,184,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 1267UV3 {hex_file(CUST,188,2)}
set-ini-val '/backup/kips/.EOS/Backup {ini_file(Backup,Path)}.ini' Backup 1305UV3 {hex_file(CUST,192,2)}
remove-ini-section './config.ini' Backup

unzip /config/ASAP-assist/ultrahand/downloads/E.zip /config/ASAP-assist/ultrahand/downloads/E/
mv /atmosphere/kips/loader.kip '/backup/kips/EOS_loader.kip'
mv /config/ASAP-assist/ultrahand/downloads/E/loader.kip '/atmosphere/kips/loader.kip'
del /config/ASAP-assist/ultrahand/downloads/
del '/backup/kips/.EOS/loader.kip'

set-ini-val './config.ini' Backup Path '/backup/kips/.EOS/Backup upd.ini'
clear hex_sum_cache
ini_file './config.ini'
ini_file '{ini_file(Backup,Path)}'

hex-by-custom-offset /atmosphere/kips/loader.kip CUST 8 {ini_file(Backup,cpuBoost)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 12 {ini_file(Backup,cpuUVL)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 252 {ini_file(Backup,cpuUVH)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 16 {ini_file(Backup,cpuVminE)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 20 {ini_file(Backup,cpuVmaxE)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 24 {ini_file(Backup,cpuVminL)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 28 {ini_file(Backup,cpuVminH)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 32 {ini_file(Backup,cpuVmaxM)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 36 {ini_file(Backup,gpuUVE)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 40 {ini_file(Backup,gpuUVM)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 44 {ini_file(Backup,gpuOFF)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 48 {ini_file(Backup,gpuVminE)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 52 {ini_file(Backup,gpuSpeedo)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 56 {ini_file(Backup,gpuVminM)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 60 {ini_file(Backup,gpuVmax)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 64 {ini_file(Backup,DRAM)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 68 {ini_file(Backup,ramVDD2)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 72 {ini_file(Backup,ramVDDQ)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 76 {ini_file(Backup,ramMHzE)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 80 {ini_file(Backup,ramMHzM)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 84 {ini_file(Backup,DVB)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 88 {ini_file(Backup,T1)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 92 {ini_file(Backup,T2)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 96 {ini_file(Backup,T3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 100 {ini_file(Backup,T4)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 104 {ini_file(Backup,T5)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 108 {ini_file(Backup,T6)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 112 {ini_file(Backup,T7)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 116 {ini_file(Backup,T8)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 120 {ini_file(Backup,T9)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 124 {ini_file(Backup,76UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 128 {ini_file(Backup,153UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 132 {ini_file(Backup,230UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 136 {ini_file(Backup,307UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 140 {ini_file(Backup,384UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 144 {ini_file(Backup,460UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 148 {ini_file(Backup,537UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 152 {ini_file(Backup,614UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 156 {ini_file(Backup,691UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 160 {ini_file(Backup,768UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 164 {ini_file(Backup,844UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 168 {ini_file(Backup,921UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 172 {ini_file(Backup,998UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 176 {ini_file(Backup,1075UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 180 {ini_file(Backup,1152UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 184 {ini_file(Backup,1228UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 188 {ini_file(Backup,1267UV3)}
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 192 {ini_file(Backup,1305UV3)}
remove-ini-section './config.ini' Backup
cp /atmosphere/kips/loader.kip '/backup/kips/.EOS/loader.kip'
del '/backup/kips/.EOS/Backup upd.ini'
exec boot
refresh


[백업 시스템]
[*0번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/EOS_s0_loader.kip'
'' = 'SD:/backup/kips/.EOS/slot_0.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/EOS_s0_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot0]
;mode=forwarder
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_0.ini' '/backup/kips/.EOS/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot0]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot0]
;mode=slot
del /backup/kips/.EOS/tmp.ini
del '/backup/kips/.EOS/slot_0.ini'
exec backup
del '/backup/kips/EOS_s0_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/EOS_s0_loader.kip' 
mv '/backup/kips/.EOS/tmp.ini' '/backup/kips/.EOS/slot_0.ini' 
#set-ini-val './config.ini' '설정 복원?slot0' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot0]
;mode=slot
try:
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_0.ini' '/backup/kips/.EOS/tmp.ini' 
exec restore
del '/backup/kips/.EOS/tmp.ini'
exec boot
del '/backup/kips/EOS_s0_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/EOS_s0_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot0]
;mode=default
del '/backup/kips/.EOS/slot_0.ini'
del '/backup/kips/EOS_s0_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot0' footer
remove-ini-key './config.ini' '설정 백업?slot0' footer
remove-ini-key './config.ini' '설정 복원?slot0' footer
refresh


[*1번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/EOS_s1_loader.kip'
'' = 'SD:/backup/kips/.EOS/slot_1.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/EOS_s1_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot1]
;mode=forwarder
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_1.ini' '/backup/kips/.EOS/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot1]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot1]
;mode=slot
del /backup/kips/.EOS/tmp.ini
del '/backup/kips/.EOS/slot_1.ini'
exec backup
del '/backup/kips/EOS_s1_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/EOS_s1_loader.kip' 
mv '/backup/kips/.EOS/tmp.ini' '/backup/kips/.EOS/slot_1.ini' 
#set-ini-val './config.ini' '설정 복원?slot1' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot1]
;mode=slot
try:
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_1.ini' '/backup/kips/.EOS/tmp.ini' 
exec restore
del '/backup/kips/.EOS/tmp.ini'
exec boot
del '/backup/kips/EOS_s1_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/EOS_s1_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot1]
;mode=default
del '/backup/kips/.EOS/slot_1.ini'
del '/backup/kips/EOS_s1_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot1' footer
remove-ini-key './config.ini' '설정 백업?slot1' footer
remove-ini-key './config.ini' '설정 복원?slot1' footer
refresh


[*2번 슬롯]
[안내문]
;mode=table
;spacing=5
;gap=0
'백업:' = 'SD:/backup/kips/EOS_s2_loader.kip'
'' = 'SD:/backup/kips/.EOS/slot_2.ini'
'' = ''

[정보]
;mode=table
;gap=30
hex_file '/backup/kips/EOS_s2_loader.kip'
json '{"00":"?","0B":"1.9.2","11":"1.2.5 or lower","28":"SC 1.2.6","46":"EOS 1.2.6","29":"SC 1.2.7","47":"EOS 1.2.7","2A":"SC 1.3.0","48":"EOS 1.3.0","2B":"SC 1.3.1","49":"EOS 1.3.1","2C":"SC 1.3.2","4A":"EOS 1.3.2"}'
'버전:' = {json({hex_file(CUST,4,1)})}

[*백업 값 확인?slot2]
;mode=forwarder
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_2.ini' '/backup/kips/.EOS/tmp.ini'
package_source './backup_info.ini'

[*백업 유형?slot2]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[설정 백업?slot2]
;mode=slot
del /backup/kips/.EOS/tmp.ini
del '/backup/kips/.EOS/slot_2.ini'
exec backup
del '/backup/kips/EOS_s2_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/backup_loader.kip' 
exec loader_backup
mv '/backup/kips/backup_loader.kip' '/backup/kips/EOS_s2_loader.kip' 
mv '/backup/kips/.EOS/tmp.ini' '/backup/kips/.EOS/slot_2.ini' 
#set-ini-val './config.ini' '설정 복원?slot2' footer '{timestamp("%Y-%m-%d %H:%M")}'
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[설정 복원?slot2]
;mode=slot
try:
del '/backup/kips/.EOS/tmp.ini'
cp '/backup/kips/.EOS/slot_2.ini' '/backup/kips/.EOS/tmp.ini' 
exec restore
del '/backup/kips/.EOS/tmp.ini'
exec boot
del '/backup/kips/EOS_s2_loader.kip'
cp '/atmosphere/kips/loader.kip' '/backup/kips/EOS_s2_loader.kip' 
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh

[백업 제거?slot2]
;mode=default
del '/backup/kips/.EOS/slot_2.ini'
del '/backup/kips/EOS_s2_loader.kip'
remove-ini-key './config.ini' '*백업 유형?slot2' footer
remove-ini-key './config.ini' '설정 백업?slot2' footer
remove-ini-key './config.ini' '설정 복원?slot2' footer
refresh


[백업 시스템]
[*추가 슬롯]
;mode=forwarder
package_source './additional_slot.ini'