;version=Post-update setup tool
;creator=Asa
;color=blue

[메인 런처]
[안내문]
;mode=table
;gap=30
'안내:' = '메인 런처는 "런처"에 생성됩니다'

[에뮤/시스낸드 (커펌)]
;mode=toggle?on
on:
    remove-ini-section '/bootloader/hekate_ipl.ini' '커펌 (eMMC/SD Card)'
    set-ini-val '/bootloader/hekate_ipl.ini' '커펌 (eMMC/SD Card)' payload bootloader/payloads/fusee.bin
    set-ini-val '/bootloader/hekate_ipl.ini' '커펌 (eMMC/SD Card)' logopath bootloader/res/bootscreen/atmosphere_b.bmp
    set-ini-val '/bootloader/hekate_ipl.ini' '커펌 (eMMC/SD Card)' icon bootloader/res/icon/fusee_nobox.bmp
off:
    remove-ini-section '/bootloader/hekate_ipl.ini' '커펌 (eMMC/SD Card)'


[시스낸드 (정펌)]
;mode=toggle?on
on:
    remove-ini-section '/bootloader/hekate_ipl.ini' '정펌 (eMMC)'
    set-ini-val '/bootloader/hekate_ipl.ini' '정펌 (eMMC)' fss0 atmosphere/package3
    set-ini-val '/bootloader/hekate_ipl.ini' '정펌 (eMMC)' stock 1
    set-ini-val '/bootloader/hekate_ipl.ini' '정펌 (eMMC)' emummc_force_disable 1
    set-ini-val '/bootloader/hekate_ipl.ini' '정펌 (eMMC)' logopath bootloader/res/bootscreen/warmboot_fix.bmp
    set-ini-val '/bootloader/hekate_ipl.ini' '정펌 (eMMC)' icon bootloader/res/icon/ofw_sys_dark_nobox.bmp
off:
    remove-ini-section '/bootloader/hekate_ipl.ini' '정펌 (eMMC)'



[L4T 런처]
[안내문]
;mode=table
;gap=30
'안내:' = 'L4T관련 OS는 "기타 런처"에 생성됩니다'

[Lineage (안드로이드)]
;mode=toggle
on:
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' l4t 1
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' boot_prefixes switchroot/android/
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' id SWANDR
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' r2p_action self
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' usb3_enable 1
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' icon bootloader/res/icon/android_nobox.bmp
    set-ini-val '/bootloader/ini/android.ini' 'Lineage OS (안드로이드)' logopath bootloader/res/bootscreen/android.bmp
off:
    delete '/bootloader/ini/android.ini'


[Lakka (에뮬레이터)]
;mode=toggle
on:
    set-ini-val '/bootloader/ini/emulator.ini' 'Lakka (에뮬레이터)' l4t 1
    set-ini-val '/bootloader/ini/emulator.ini' 'Lakka (에뮬레이터)' boot_prefixes lakka/boot/
    set-ini-val '/bootloader/ini/emulator.ini' 'Lakka (에뮬레이터)' id SWR-LAK
    set-ini-val '/bootloader/ini/emulator.ini' 'Lakka (에뮬레이터)' icon bootloader/res/icon/lakka_nobox.bmp
    set-ini-val '/bootloader/ini/emulator.ini' 'Lakka (에뮬레이터)' logopath bootloader/res/bootscreen/lakka.bmp
off:
    delete '/bootloader/ini/emulator.ini'


[Ubuntu (리눅스)]
;mode=toggle
on:
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' l4t 1
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' boot_prefixes /switchroot/ubuntu/
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' uart_port 0
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' id SWR-UBU
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' r2p_action self
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' usb3_enable 1
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' icon bootloader/res/icon/ubuntu_nobox.bmp
    set-ini-val '/bootloader/ini/linux.ini' 'Ubuntu (리눅스)' logopath bootloader/res/bootscreen/ubuntu.bmp
off:
    delete '/bootloader/ini/linux.ini'