;title=Memory Config
;version=0.1.4  ㅤㅤㅤㅤㅤㅤ
;creator=ppkantorski
;color=blue

[@버퍼 설정]

[버퍼 설정]
[경고문]
;mode=table
;alignment=right
;spacing=5
;gap=5
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '잘 알지 못하는 경우 설정하지 마십시오'
'' = '프리징 및 오류를 발생시킬 수 있습니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯  ㅤㅤㅤㅤㅤ'

[안내문]
;mode=table
;alignment=right
;spacing=5
;gap=35
'안내:' = 'Ultrahand, 오버레이, 패키지의'
'' = '메모리 버퍼 값을 조정합니다'
'' = ''
'해법:' = '프리징, 오류가 발생하는 경우, 다음 실행'
'' = '추가 설정→동작→버퍼 제거, Heap 리셋'

[*복사 버퍼]
;mode=option
list_source '(256, 512, 1024, 2048, 4096, 8192, 12288, 16384, 20480, 24576, 28672, 32768, 36864, 40960, 45056, 65536)'
set-ini-val /config/ASAP-assist/ultrahand/config.ini ultrahand copy_buffer_size {list_source(*)}
set-footer '{list_source(*)}'

[*다운로드 버퍼]
;mode=option
list_source '(256, 512, 1024, 2048, 4096, 8192, 12288, 16384, 20480, 24576, 28672, 32768, 36864, 40960, 45056, 65536, 98304, 131072, 262144)'
set-ini-val /config/ASAP-assist/ultrahand/config.ini ultrahand download_buffer_size {list_source(*)}
set-footer '{list_source(*)}'

[*압축해제 버퍼]
;mode=option
list_source '(256, 512, 1024, 2048, 4096, 8192, 12288, 16384, 20480, 24576, 28672, 32768, 36864, 40960, 45056, 65536)'
set-ini-val /config/ASAP-assist/ultrahand/config.ini ultrahand unzip_buffer_size {list_source(*)}
set-footer '{list_source(*)}'

[*Hex 버퍼]
;mode=option
list_source '(256, 512, 1024, 2048, 4096, 8192, 12288, 16384, 20480, 24576, 28672, 32768, 36864, 40960, 45056, 65536)'
set-ini-val /config/ASAP-assist/ultrahand/config.ini ultrahand hex_buffer_size {list_source(*)}
set-footer '{list_source(*)}'



[@추가 설정]

[쓰레드 설정]
[*Heap 인터프리터]
;mode=option
list_source '(0x4000, 0x5000, 0x6000, 0x7000, 0x8000, 0x9000, 0x10000, 0x11000, 0x12000, 0x13000, 0x14000, 0x16000)'
set-ini-val /config/ASAP-assist/ultrahand/config.ini ultrahand interpreter_heap {list_source(*)}
set-footer '{list_source(*)}'

[동작]
[버퍼 제거]
remove-ini-key /config/ASAP-assist/ultrahand/config.ini ultrahand copy_buffer_size
remove-ini-key /config/ASAP-assist/ultrahand/config.ini ultrahand download_buffer_size
remove-ini-key /config/ASAP-assist/ultrahand/config.ini ultrahand unzip_buffer_size
remove-ini-key /config/ASAP-assist/ultrahand/config.ini ultrahand hex_buffer_size
remove-ini-section ./config.ini '*Copy Buffer'
remove-ini-section ./config.ini '*Download Buffer'
remove-ini-section ./config.ini '*Unzip Buffer'
remove-ini-section ./config.ini '*Hex Buffer'

[Heap 리셋]
remove-ini-key /config/ASAP-assist/ultrahand/config.ini ultrahand interpreter_heap
remove-ini-section ./config.ini '*Interpreter Heap'
set-ini-section