;version=Post-update setup tool
;creator=Asa
;color=blue

[풀 메모리 모드]
[경고문]
;mode=table
;alignment=right
;spacing=5
;gap=10
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = 'hbmenu 타이틀 앱에선 사용 불가합니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ '

[안내문]
;mode=table
;spacing=5
;gap=30
'안내:' = 'hbmenu를 메모리 제한 없이 사용합니다'
'' = '타이틀 + A 홀드 진입을 활성화합니다'

[타이틀]
;mode=toggle?on
on:
    set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_any_app true
off:
    set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_any_app false

[애플릿 모드]
[경고문]
;mode=table
;alignment=right
;spacing=5
;gap=10
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '애플릿 모드에서는 메모리가 제한됩니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ '

[안내문]
;mode=table
;spacing=5
;gap=0
'안내:' = 'hbmenu의 앨범 진입 버튼을 지정합니다'
'' = '단일 버튼 혹은 조합 키로 지정 가능'
'' = ''

[기본 키]
;mode=table
;gap=30
;info_text_color=00FFDD
'기본:' = 'A 홀드'

[*앨범]
[애플릿 모드] 
;mode=option 
json_file_source './json/hb_applet_override.json' label
set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_key {json_file_source(*,key)}
set-footer '{json_file_source(*,label)}'