;version=Post-update setup tool
;creator=Asa
;color=blue

[부팅 낸드 설정]
[경고문]
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '기본 커펌으로 부팅할 낸드를 지정합니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ'

[안내문]
;mode=table
;spacing=5
;gap=0
'안내:' = '미리 지정한 낸드로만 부팅할 수 있습니다'
'' = '실수로 인한 시스낸드 사용을 방지합니다'
'' = ''

[런처]
;mode=table
;gap=30
;info_text_color=00FFDD
'런처:' = '커펌 (eMMC/SD Card)'

[*기본 낸드]
;mode=option
json_file_source './json/default_nand.json' label
set-ini-val '/emummc/emummc.ini' emummc enabled {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'

[시스낸드 전용 설정]
[경고문]
;mode=table
;alignment=right
;spacing=0
;gap=0
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = '일반적으로 사용을 권장하지 않습니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ '

[안내문]
;mode=table
;spacing=5
;gap=30
'exosphеre:' = '기기의 시리얼 넘버를 변조합니다'
'90 DNS:' = '닌텐도 서버와 연결을 차단합니다'

[exosphеre]
;mode=toggle?off
on:
    set-ini-val '/atmosphere/config/exosphere.ini' exosphere blank_prodinfo_sysmmc 1
off:
    set-ini-val '/atmosphere/config/exosphere.ini' exosphere blank_prodinfo_sysmmc 0

[90 DNS]
;mode=toggle?off
on:
    mv '/atmosphere/hosts/sysdns.txt' '/atmosphere/hosts/sysmmc.txt'
off:
    mv '/atmosphere/hosts/sysmmc.txt' '/atmosphere/hosts/sysdns.txt'