;version=Post-update setup tool
;creator=Asa
;color=blue

[@기본 설정]

[커펌 낸드]
[*낸드 설정]
;mode=forwarder
package_source './nand_setting.ini'

[홈브류 메뉴]
[*진입 키 설정]
;mode=forwarder
package_source './hb_override.ini'

[앱 사용 전환]
[*홈브류]
;mode=toggle
filter '/switch/prod.keys'
filter '/switch/title.keys'
filter '/switch/.packages'
filter '/switch/.overlays'
filter '/switch/ASAP-Updater'
filter '/switch/NX-Activity-Log'
filter '/switch/sys-clk-manager'
filter '/switch/sys-con'
on:
   file_source '/switch/*/'
   mv {file_source} '/config/ASAP-assist/Homebrews/{file_name}/'
off:
   file_source '/config/ASAP-assist/Homebrews/*/'
   mv {file_source} '/switch/{file_name}/'

[*오버레이]
;mode=toggle
filter '/switch/.overlays/ovlSysmodules.ovl'
filter '/switch/.overlays/ovlmenu.ovl'
filter '/switch/.overlays/sys-clk-overlay.ovl'
filter '/switch/.overlays/sys-patch-overlay.ovl'
on:
    file_source '/switch/.overlays/*.ovl'
    mkdir '/switch/.overlays/.offload/'
    mv {file_source} '/switch/.overlays/.offload/'
off:
    file_source '/switch/.overlays/.offload/*.ovl'
    mv {file_source} '/switch/.overlays/'

[*컨트롤러]
;mode=forwarder
package_source './use_conv.ini'



[@추가 설정]

[Hekate 설정]
[안내문]
;system=mariko
;mode=table
;spacing=10
;gap=30
'안내:' = '자동 부팅은 항상 커펌으로 재부팅합니다'
'' = 'Erista 유저는 HOS 종료를 끄십시오'

[*런처 추가/제거]
;mode=forwarder
package_source './add_launcher.ini'

[자동 부팅]
;mode=toggle?off
on:
    set-ini-val '/bootloader/hekate_ipl.ini' config autoboot 1
    set-ini-val '/bootloader/hekate_ipl.ini' config autoboot_list 0
off:
    set-ini-val '/bootloader/hekate_ipl.ini' config autoboot 0
    set-ini-val '/bootloader/hekate_ipl.ini' config autoboot_list 0

[부팅 화면 대기 시간]
;mode=step_trackbar
;min_value=0
;max_value=20
;units=초
set-ini-val /bootloader/hekate_ipl.ini config bootwait {value}

[HOS 종료]
;mode=toggle?on
on:
    set-ini-val '/bootloader/hekate_ipl.ini' config autohosoff 2
off:
    set-ini-val '/bootloader/hekate_ipl.ini' config autohosoff 1

[메모리]
[*Buffer 조정]
;mode=forwarder
package_source './buffer.ini'    