;version=Post-update setup tool
;creator=Asa
;color=blue

[컨트롤러]
[경고문]
;mode=table
;alignment=right
;spacing=5
;gap=5
;section_text_color=EE2323
;info_text_color=EE2323
'주의:' = 'ASAP 지원 범위 외의 HOS 버전 사용 시,'
'' = '커스텀 펌웨어 부팅에 실패할 수 있습니다'
'' = '¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ ㅤㅤㅤㅤ'

[안내문]
;mode=table
;spacing=5
;gap=35
'안내:' = '서드파티 컨트롤러 연결을 허용합니다'
'' = '적용을 위해 자동으로 재부팅합니다'
'' = ''
'MissionControl:' = '무선 컨트롤러 대상'
'Sys-Con:' = '유선 컨트롤러 대상'

[MissionControl]
;mode=toggle
on:
    cp '/config/ASAP-assist/Controller/MissionControl/010000000000bd00/' '/atmosphere/contents/010000000000bd00/'
    cp '/config/ASAP-assist/Controller/MissionControl/bluetooth_patches/' '/atmosphere/exefs_patches/bluetooth_patches/'
    cp '/config/ASAP-assist/Controller/MissionControl/btm_patches/' '/atmosphere/exefs_patches/btm_patches/'
    mv '/config/ASAP-assist/Controller/MissionControl/MissionControl/' '/config/MissionControl/'
    set-ini-val './config.ini' 'MissionControl' footer On
    reboot boot '커펌 (eMMC/SD Card)'
off:
    del '/atmosphere/contents/010000000000bd00/'
    del '/atmosphere/exefs_patches/bluetooth_patches/'
    del '/atmosphere/exefs_patches/btm_patches/'
    mv '/config/MissionControl/' '/config/ASAP-assist/Controller/MissionControl/MissionControl/'
    set-ini-val './config.ini' 'MissionControl' footer Off
    reboot boot '커펌 (eMMC/SD Card)'
    
[Sys-Con]
;mode=toggle
on:
    cp '/config/ASAP-assist/Controller/sys-con/690000000000000D/' '/atmosphere/contents/690000000000000D/'
    mv '/config/ASAP-assist/Controller/sys-con/sys-con/' '/config/sys-con/'
    mv '/config/ASAP-assist/Controller/sys-con/switch/sys-con/' '/switch/sys-con/'
    set-ini-val './config.ini' 'Sys-Con' footer On
    reboot boot '커펌 (eMMC/SD Card)'
off:
    del '/atmosphere/contents/690000000000000D/'
    mv '/config/sys-con/' '/config/ASAP-assist/Controller/sys-con/sys-con/'
    mv '/switch/sys-con/' '/config/ASAP-assist/Controller/sys-con/switch/sys-con/'
    set-ini-val './config.ini' 'Sys-Con' footer Off
    reboot boot '커펌 (eMMC/SD Card)'